.ostc-ci: fix writable bitbake directory check
The path to check was not updated after the private/public cache was
split. It works because we have the legacy structure present on our
cache disk. This mistake interferes with automatic preparation of a new
runner.

Signed-off-by: Zygmunt Krynicki <zygmunt.krynicki@huawei.com>
Change-Id: I77d127331f926e59459ca54919770202cca3e21a

diff --git a/.ostc-ci/build-generic.yaml b/.ostc-ci/build-generic.yaml
--- a/.ostc-ci/build-generic.yaml
+++ b/.ostc-ci/build-generic.yaml
@@ -113,10 +113,10 @@ include:
         echo "precondition failed - cannot define just one of OHOS_CI_DEVTOOL_RECIPE_NAME and OHOS_CI_DEVTOOL_LAYER_PATH"
         exit 1
       fi
-    # Bitbake is configured to use /var/shared/bitbake directory
-    # for both the download directory and the sstate-cache.
-    - test -w /var/shared/bitbake || (
-        echo "precondition failed - expected /var/shared/bitbake to be writable"
+    # Bitbake is configured to use /var/shared/$OHOS_BUILD_CACHE/bitbake
+    # directory for both the download directory and the sstate-cache.
+    - test -w /var/shared/$OHOS_BUILD_CACHE/bitbake || (
+        echo "precondition failed - expected /var/shared/$OHOS_BUILD_CACHE/bitbake to be writable"
         && exit 1 )
     # Log available disk space on the persistent shared disk.
     - df -h /var/shared/bitbake
